default_language_version:
    python: python3

ci:
    autofix_prs: true
    autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
    # submodules: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
            exclude: "setup.cfg"
          - id: trailing-whitespace
            exclude: |
                (?x)(
                    docs/|
                    setup.cfg
                    )
          - id: check-case-conflict
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: check-added-large-files
          - id: check-docstring-first
          - id: detect-private-key

    - repo: https://github.com/PyCQA/docformatter
      rev: 06907d0267368b49b9180eed423fae5697c1e909 # todo: fix for docformatter after last 1.7.5
      hooks:
          - id: docformatter
            additional_dependencies: [tomli]
            args: ["--in-place"]

    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.19
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-gfm
                - mdformat-black
                - mdformat_frontmatter
            exclude: |
                (?x)(
                    docs/|
                    README.md
                    )

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.3
      hooks:
          - id: ruff
            args: ["--fix"]
          - id: ruff-format
          - id: ruff

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            files: \.(json|yml|yaml|toml)
            # https://prettier.io/docs/en/options.html#print-width
            args: ["--print-width=120"]
