# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py

# Build documentation with MkDocs
mkdocs:
 configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements_dev.txt
    - method: pip
      path: .[extra]
